/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/B4BHzJK9k9E
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function UI() {
  return (
    <div className="flex flex-col h-screen">
      <header className="flex items-center justify-between px-4 py-2 border-b">
        <h1 className="text-lg font-semibold">Longevity Copilot</h1>
        <Avatar>
          <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
          <AvatarFallback>AC</AvatarFallback>
        </Avatar>
      </header>
      <main className="flex-1 overflow-y-auto p-4 space-y-4">
        <div className="flex items-end space-x-2">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
          <div className="p-2 rounded-lg bg-gray-100 dark:bg-gray-800">
            <p className="text-sm">Hello! How's your longevity progress?</p>
          </div>
        </div>
        <div className="flex items-end space-x-2 ml-auto">
          <div className="p-2 rounded-lg bg-blue-500 text-white">
            <p className="text-sm">
              It's going great! I've been following the recommended routine.
            </p>
          </div>
          <Avatar className="w-10 h-10">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
        </div>
        <div className="flex items-end space-x-2">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
            <AvatarFallback>AC</AvatarFallback>
          </Avatar>
          <div className="p-2 rounded-lg bg-gray-100 dark:bg-gray-800">
            <p className="text-sm">That's awesome! Keep it up! 🎉</p>
          </div>
        </div>
      </main>
      <div className="p-4 border-t">
        <form className="flex items-center space-x-2">
          <Input className="flex-1" placeholder="Type a message" />
          <Button size="icon" variant="outline">
            <SmileIcon className="h-6 w-6" />
          </Button>
          <Button size="icon" type="submit">
            <SendIcon className="h-6 w-6" />
          </Button>
        </form>
      </div>
      <section className="flex flex-col items-center p-4 border-t">
        <h2 className="text-lg font-semibold mb-2">Next Selfie in:</h2>
        <div className="text-4xl font-bold">00:59:45</div>
        <Button className="mt-4">Take Selfie Now</Button>
      </section>
    </div>
  );
}

function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  );
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  );
}
